name: BuildAndTest

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
            
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
        
      - name: Build Gradle
        run: ./gradlew build
        
